### ISSUE TITLE
Decide on names

### ISSUE THREAD

**Issue by AverageMarcus** [TeamSuperAwesome/ISISBattleBots#3]
@DanNixon / @eXeC64 - Did we assign a name to each bot? If so which is which?

1) ![img_20150619_144722](https://cloud.githubusercontent.com/assets/3384072/8256653/5cab7fa8-16a0-11e5-8544-cb6f2d8201d3.jpg)
2) ![img_20150619_144833](https://cloud.githubusercontent.com/assets/3384072/8256655/5cb0c65c-16a0-11e5-8fc1-b2ee6dbdc73a.jpg)
3) ![img_20150619_144857](https://cloud.githubusercontent.com/assets/3384072/8256654/5caeaf2a-16a0-11e5-867a-6e51a0884827.jpg)

**Comment by eXeC64** [comment]
Alice is brown, Bob is green, Eve is blue.

**Comment by AverageMarcus** [comment]
Awesome! :+1: Cheers!

**Comment by DanNixon** [comment]
It's trivially easy to change anyway.

**Comment by AverageMarcus** [comment]
I just needed a decision so I could select the robot to control by a picture
